# Minimal Pipeline for test-deployment

trigger:
- master

pool:
  vmImage: 'ubuntu:16.04'

  container: ubuntu:16.04

steps:
- task: AzureResourceManagerTemplateDeployment@3
#deployment of the VNET
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'France Central'
    templateLocation: 'Linked artifact'
    csmFile: './vnet/VNET.json'
    csmParametersFile: './vnet/parametersFile.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
#deployment of the PPG
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'France Central'
    templateLocation: 'Linked artifact'
    csmFile: './Proximity-placement-group/template.json'
    csmParametersFile: './Proximity-placement-group/parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
#deployment of the PPG-1
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'France Central'
    templateLocation: 'Linked artifact'
    csmFile: './Proximity-placement-group/template.json'
    csmParametersFile: './Proximity-placement-group/parameters-2.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
#deployment of the diagnostics storage account
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'France Central'
    templateLocation: 'Linked artifact'
    csmFile: './storage_account/template.json'
    csmParametersFile: './storage_account/parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
#deployment of the VM node 1 cluster pacemaker
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'France Central'
    templateLocation: 'Linked artifact'
    csmFile: './VM/template.json'
    csmParametersFile: './VM/parametersFile.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
#deployment of the VM node 2 cluster pacemaker
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'France Central'
    templateLocation: 'Linked artifact'
    csmFile: './VM/template.json'
    csmParametersFile: './VM/parametersFile1.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
#deployment of LB
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'suscription_Helo'
    subscriptionId: '714f1d31-e6fc-4955-acef-4e261636a95e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Pacemaker_cluster'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: './LoadBalancer/templateLB.json'
    csmParametersFile: './LoadBalancer/parametersLB.json'
    deploymentMode: 'Incremental'

